---
title: "Finding_Sig_Genes"
author: "Connor Gagen, Julia Keefe, Paloma Peters, Anna Mellizo Kroll, Anna Broerman"
date: "2025-04-04"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(IRanges)
library(dplyr)
library(tidyr)
library(tibble)
library(readr)
library(ggplot2)
library(purrr)
library(magrittr)
library(pheatmap)
library(textshape)
library(Rcpp)
library(DESeq2)
library(knitr)
```

# Goal: script our RNAseq analysis pipeline to find genes changing significantly across time from dox exposure. 

## Importing counts values
```{r import counts from Salmon}
# This loads in the counts from the NF core run
counts_matrix <- read.table("/scratch/Shares/rinnclass/MASTER_CLASS/STUDENTS/juke6537/MASTER_CLASS/data/salmon.merged.gene_counts.tsv", header=TRUE, row.names=1)

# This will prepare the counts for DESEQ by creating g2s
g2s <- data.frame(
  gene_id = rownames(counts_matrix),
  gene_name = counts_matrix[, 1]
)
# This removes the gene name from the counts matrix such that it is only numeric values
counts_matrix <- counts_matrix[ , -1]
# Round the values within the counts matrix. 
counts_integer <- round(counts_matrix)

```

## Creating sample sheet for DESeq from counts file
```{r creating DESeq sample sheet}
# This creates the data frame with the same columns as the counts_matrix
deseq_samples <- data.frame(
  sample_id = colnames(counts_matrix))
# Splits the sample_id to create a columns for time point and replicate columns
split_values <- strsplit(deseq_samples$sample_id, "_")
# This extracts the time point and the replicate info
time_values <- sapply(split_values, function(x) x[[2]])
replicate_values <- sapply(split_values, function(x) x[[3]])
# This will place the time point and replicate into the data frame.
deseq_samples$time_point <- time_values
deseq_samples$replicate <- replicate_values
# This converts the time point and replicate data into a factor.
deseq_samples$time_point <- factor(deseq_samples$time_point)
deseq_samples$replicate <- factor(deseq_samples$replicate)

```

## Running DESEQ2
```{r running deseq2}
# Test to see if the sample sheet matches the corresponding deseq_samples data frame
stopifnot(all(colnames(counts_integer) == rownames(deseq_samples$sample_id)))
# Sets up the dds
dds_time_point <- DESeqDataSetFromMatrix(countData = counts_integer,
                              colData = deseq_samples,
                              design = ~ time_point)
# Runs the DESeqq
dds_time_point <- DESeq(dds_time_point)
```

## Extracting results for each time point from DESEQ dds
```{r compile DESEQ2 results}

# retrieves the names corresponding to the different time points 
result_names <- resultsNames(dds_time_point)
# Removes the first entry from deseq which is the baseline. 
results_names <- result_names[-1]

# Setting up data frame 
res_df <- data.frame("gene_id" = character(), 
                     "baseMean" = numeric(), 
                     "log2FoldChange" = numeric(), 
                     "lfcSE" = numeric(),
                     "stat" = numeric(),
                     "pvalue" = numeric(),
                     "padj" = numeric(),
                     "gene_name" = character(),
                     "result_name" = character())

# run for loop to retreive results from all time comparisons in dds
for(i in 1:length(results_names)) {
  results_name <- results_names[i]
  res <- results(dds_time_point, name = results_name)
  tmp_res_df <- res %>% 
    as.data.frame() %>%
    rownames_to_column("gene_id") %>%
    merge(g2s) %>%
    mutate(result_name = results_name)
  res_df <- bind_rows(res_df, tmp_res_df)
  
}

```

##  Filtering to significant results P <0.05 and LFC abs(1)
```{r filtering DESEQ results to LFC > abs(1)& P <0.05}

filtered_res_df <- res_df %>%
  filter(padj < 0.05, abs(log2FoldChange) > 1)

unique_sig_genes <- unique(filtered_res_df$gene_id)
```
