---
title: "TPM_Sig_Genes"
author: "Connor Gagen, Julia Keefe, Paloma Peters, Anna Mellizo Kroll, Anna Broerman"
date: "2025-04-04"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(IRanges)
library(dplyr)
library(tidyr)
library(tibble)
library(readr)
library(ggplot2)
library(purrr)
library(magrittr)
library(pheatmap)
library(textshape)
library(Rcpp)
library(DESeq2)
library(matrixStats)
library(knitr)
```

# Import TPM file from Salmon after DESeq
```{r import counts and TPM from Salmon}
# loading and preparing TPM file from Salmon

TPM <- read.table("/scratch/Shares/rinnclass/MASTER_CLASS/STUDENTS/juke6537/MASTER_CLASS/data/salmon.merged.gene_tpm.tsv", header=TRUE, row.names=1)

# Delete gene names (as needed)
TPM <- TPM[,-1]

# Filtering for TPM of at least 1 across samples
TPM_filtered <- TPM[rowSums(TPM) > 1, ]
# Checking that all TPM <1 have been removed
any(rowSums(TPM_filtered) < 1)
any(rowSums(TPM) < 1)

```

# Calculating the replicate mean and standard deviation for each gene in each time point
```{r making table of mean and sd TPM value for each gene for each time point}

# Assigning time and replicate values
time_points <- c("0", "12", "24", "48", "96")
replicates <- c("_1", "_2", "_3")

# Creating list for results
average_and_stddev_values <- list()
# Putting each object into the for loop as "tp"
for (tp in time_points) {
  cols <- grep(paste0("WT_", tp, "_"), colnames(TPM_filtered))
  avg <- rowMeans(TPM_filtered[, cols])
  std_dev <- apply(TPM_filtered[, cols], 1, sd)
  std_dev <- data.frame(std_dev)
  combined <- cbind(avg, std_dev)
  average_and_stddev_values <- c(average_and_stddev_values, list(combined))
}
# Converting the list to a data frame
average_and_stddev_values <- do.call(cbind, average_and_stddev_values)
# Adding column names for the time points in terms of average (avg) and standard deviation (sd)
colnames(average_and_stddev_values) <- paste0(rep(time_points, each = 2), c("_avg", "_sd"))
```
